### ISSUE TITLE
SQLite: wrong introspection?

### ISSUE THREAD

**Issue by mikoim** [roojs/PDO_DataObject#12]
SQLite introspection seems not to be able to handle VARCHAR. Eliminating unnecessary whitespace from the column type would avoid this issue? This issue does not reproduce on MySQL and PostgreSQL.

```
[Fri Jul  3 18:29:02 2020] PHP Fatal error:
Uncaught PDO_DataObject_Exception_InvalidConfig:
*****************************************************************
**               WARNING UNKNOWN TYPE                          **
** Found column 'uri', of type  'VARCHAR '            **
** Please submit a bug, describe what type you expect this     **
** column  to be                                               **
*****************************************************************
```

```
#0 /src/vendor/roojs/pdo_dataobject/PDO/DataObject.php(5844): PDO_DataObject_Exception::factory()
#1 /src/vendor/roojs/pdo_dataobject/PDO/DataObject/Generator/Column.php(267): PDO_DataObject->raise()
#2 /src/vendor/roojs/pdo_dataobject/PDO/DataObject/Generator/Table.php(165): PDO_DataObject_Generator_Column->__construct()
#3 /src/vendor/roojs/pdo_dataobject/PDO/DataObject/Generator/Table.php(67): PDO_DataObject_Generator_Table->readFromDB()
#4 /src/vendor/roojs/pdo_dataobject/PDO/DataObject/Generator.php(468): PDO_DataObject_Generator_Table->__construct()
#5 /src/vendor/roojs/pdo_dataobject/PDO/DataObject/Generator.php(438): PDO_DataObject_Generator->newTable()
#6 /src/vendor/roojs/pdo_dataobject/PDO/DataObject/Generator.php(330): PDO_DataObject_Generator->readTableList()
#7 /src/vendor/roojs/pdo_dataobject/PDO/DataObject.php(3402): PDO_DataObject_Generator->databaseStructureProxy()
#8 /src/vendor/roojs/pdo_dataobject/PDO/DataObject.php(3647): PDO_DataObject->databaseStructure()
#9 /src/vendor/roojs/pdo_dataobject/PDO/DataObject.php(3846): PDO_DataObject->tableColumns()
#10 /src/vendor/roojs/pdo_dataobject/PDO/DataObject.php(1242): PDO_DataObject->whereToString()
#11 /src/vendor/roojs/pdo_dataobject/PDO/DataObject.php(1004): PDO_DataObject->find()
```

```
CREATE TABLE IF NOT EXISTS "imgcache" (
    id     INTEGER PRIMARY KEY,
    uri    VARCHAR (255),
    host   VARCHAR (255),
    name   VARCHAR (255),
    size   INTEGER NOT NULL,
    md5    CHAR (32) NOT NULL,
    width  SMALLINT NOT NULL,
    height SMALLINT NOT NULL,
    mime   VARCHAR (50) NOT NULL,
    time   INTEGER NOT NULL,
    rank   SMALLINT NOT NULL DEFAULT 0,
    memo   TEXT
);
CREATE INDEX "idx_imgcache_uri" ON "imgcache" ("uri");
CREATE INDEX "idx_imgcache_time" ON "imgcache" ("time");
CREATE INDEX "idx_imgcache_unique" ON "imgcache" ("size", "md5", "mime");
```

### environment
```
PHP Version => 8.0.0alpha1

pdo_sqlite

PDO Driver for SQLite 3.x => enabled
SQLite Library => 3.32.3

PDO_DataObject: dev-master
```

**Comment by mikoim** [comment]
## test code
```php
<?php
require_once "vendor/autoload.php";

class Foo extends PDO_DataObject
{
    public function __construct()
    {
        parent::__construct();
        $this->__table = 'imgcache';
    }
}

PDO_DataObject::config(['database' => 'sqlite::memory:', 'proxy' => true]);

$foo = new Foo();
$foo->PDO()->query('CREATE TABLE IF NOT EXISTS "imgcache" (
    id     INTEGER PRIMARY KEY,
    foobar VARCHAR (255)
);');

$foo->get(); // PHP Fatal error:  Uncaught PDO_DataObject_Exception_InvalidConfig
```

**Comment by roojs** [comment]
Thanks - can you try the fix above

**Comment by mikoim** [comment]
it works well. thank you!
